/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#fffbff",
        "surface-bright": "#faf8ff",
        "secondary": "#6b38d4",
        "on-tertiary-fixed-variant": "#004395",
        "secondary-fixed-dim": "#d0bcff",
        "on-primary-container": "#dad7ff",
        "tertiary-container": "#005cc6",
        "error-container": "#ffdad6",
        "primary-fixed": "#e2dfff",
        "surface-container-high": "#e2e7ff",
        "on-primary": "#ffffff",
        "on-surface": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-primary-fixed-variant": "#3323cc",
        "background": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        "primary-container": "#4f46e5",
        "tertiary-fixed-dim": "#adc6ff",
        "secondary-container": "#8455ef",
        "primary": "#3525cd",
        "surface-container-highest": "#dae2fd",
        "inverse-surface": "#283044",
        "on-surface-variant": "#464555",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "on-background": "#131b2e",
        "on-secondary-fixed-variant": "#5516be",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eef0ff",
        "tertiary": "#004598",
        "on-tertiary-container": "#cedbff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#23005c",
        "secondary-fixed": "#e9ddff",
        "surface-tint": "#4d44e3",
        "surface-container-low": "#f2f3ff",
        "outline-variant": "#c7c4d8",
        "surface": "#faf8ff",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "#93000a",
        "outline": "#777587",
        "on-tertiary-fixed": "#001a42",
        "surface-container-lowest": "#ffffff",

        // Cosmic and Brand helpers
        cosmic: {
          950: '#070a13',
          900: '#0a0e1c',
          800: '#11182c',
          700: '#1b243d',
        },
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        '3xl': '24px',
        '4xl': '32px',
      },
      spacing: {
        "gutter-desktop": "2rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "margin-desktop": "3.5rem",
        "gutter": "1.5rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "margin-tablet": "2rem",
      },
      fontFamily: {
        sans: ['"Be Vietnam Pro"', '"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        "display-hero": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-lg": ['"Be Vietnam Pro"', 'sans-serif'],
        "headline-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
        "headline-xl-mobile": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-md": ['"Be Vietnam Pro"', 'sans-serif'],
        "headline-xl": ['"Plus Jakarta Sans"', 'sans-serif'],
        "headline-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-sm": ['"Be Vietnam Pro"', 'sans-serif'],
        "display-hero-mobile": ['"Plus Jakarta Sans"', 'sans-serif'],
        "title-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "headline-lg": ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "68px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "800" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      boxShadow: {
        'card': '0 4px 20px -2px rgba(0, 0, 0, 0.06), 0 2px 6px -1px rgba(0, 0, 0, 0.03)',
        'floating': '0 12px 35px -5px rgba(0, 0, 0, 0.12), 0 4px 12px -2px rgba(0, 0, 0, 0.06)',
        'glow': '0 0 35px -5px rgba(99, 102, 241, 0.4)',
        'glow-warm': '0 0 35px -5px rgba(245, 158, 11, 0.35)',
      },
    },
  },
  plugins: [],
};
